# -*- coding: utf-8 -*-
"""ml-classification-models-comparison_M.ALZeiter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifG2SZkquDLYYcYcZtDK7F5GST3g9rlg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import time

iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target
iris_df['species'] = iris_df['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

cancer = load_breast_cancer()
cancer_df = pd.DataFrame(cancer.data, columns=cancer.feature_names)
cancer_df['target'] = cancer.target
cancer_df['diagnosis'] = cancer_df['target'].map({0: 'malignant', 1: 'benign'})

print("------- Iris Dataset -------")
print(f"Shape: {iris_df.shape}")
print(iris_df.head())
print(iris_df.info())
print(iris_df.isnull().sum())

print("\n------- Cancer Dataset -------")
print(f"Shape: {cancer_df.shape}")
print(cancer_df.head())
print(cancer_df.info())
print(cancer_df.isnull().sum())

plt.figure(figsize=(6, 4))
iris_df['species'].value_counts().plot(kind='bar')
plt.title('Iris Species Distribution')
plt.show()


sns.pairplot(iris_df, hue='species', height=2.5)
plt.show()

important_features = cancer_df.columns[:10]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.countplot(x='diagnosis', data=cancer_df, ax=axes[0])
axes[0].set_title('Cancer Diagnosis Distribution')

sns.heatmap(
    cancer_df[important_features].corr(),
    annot=True,
    cmap='coolwarm',
    ax=axes[1]
)
axes[1].set_title('Feature Correlation')

plt.tight_layout()
plt.show()

X_iris = iris.data
y_iris = iris.target

X_iris_train, X_iris_test, y_iris_train, y_iris_test = train_test_split(
    X_iris, y_iris, test_size=0.2, random_state=42, stratify=y_iris)

scaler_iris = StandardScaler()
X_iris_train_scaled = scaler_iris.fit_transform(X_iris_train)
X_iris_test_scaled = scaler_iris.transform(X_iris_test)

X_cancer = cancer.data
y_cancer = cancer.target


X_cancer_train, X_cancer_test, y_cancer_train, y_cancer_test = train_test_split(
    X_cancer, y_cancer, test_size=0.2, random_state=42, stratify=y_cancer)

scaler_cancer = StandardScaler()
X_cancer_train_scaled = scaler_cancer.fit_transform(X_cancer_train)
X_cancer_test_scaled = scaler_cancer.transform(X_cancer_test)

models = {
    'Logistic Regression': LogisticRegression(random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Naive Bayes': GaussianNB(),
    'SVM': SVC(kernel='linear', random_state=42)
}

iris_results = {}

for name, model in models.items():
    print(f"\n------- {name} - Iris Dataset -------")

    start_time = time.time()
    model.fit(X_iris_train_scaled, y_iris_train)
    training_time = time.time() - start_time
    start_time = time.time()

    y_pred_train = model.predict(X_iris_train_scaled)
    y_pred_test = model.predict(X_iris_test_scaled)
    prediction_time = time.time() - start_time

    train_accuracy = accuracy_score(y_iris_train, y_pred_train)
    test_accuracy = accuracy_score(y_iris_test, y_pred_test)

    print(f"Training Accuracy: {train_accuracy:.4f}")
    print(f"Test Accuracy: {test_accuracy:.4f}")
    print(f"Training Time: {training_time:.4f} seconds")
    print(f"Prediction Time: {prediction_time:.4f} seconds")

    iris_results[name] = {
        'model': model,
        'train_accuracy': train_accuracy,
        'test_accuracy': test_accuracy,
        'training_time': training_time,
        'prediction_time': prediction_time,
        'y_pred_test': y_pred_test
    }

cancer_results = {}

for name, model in models.items():
    print(f"\n------- {name} - Cancer Dataset -------")

    if name == 'Logistic Regression':
        model = LogisticRegression(random_state=42)
    elif name == 'Decision Tree':
        model = DecisionTreeClassifier(random_state=42)
    elif name == 'Naive Bayes':
        model = GaussianNB()
    elif name == 'SVM':
        model = SVC(kernel='linear', random_state=42)

    start_time = time.time()
    model.fit(X_cancer_train_scaled, y_cancer_train)
    training_time = time.time() - start_time

    start_time = time.time()
    y_pred_train = model.predict(X_cancer_train_scaled)
    y_pred_test = model.predict(X_cancer_test_scaled)
    prediction_time = time.time() - start_time


    train_accuracy = accuracy_score(y_cancer_train, y_pred_train)
    test_accuracy = accuracy_score(y_cancer_test, y_pred_test)

    print(f"Training Accuracy: {train_accuracy:.4f}")
    print(f"Test Accuracy: {test_accuracy:.4f}")
    print(f"Training Time: {training_time:.4f} seconds")
    print(f"Prediction Time: {prediction_time:.4f} seconds")


    cancer_results[name] = {
        'model': model,
        'train_accuracy': train_accuracy,
        'test_accuracy': test_accuracy,
        'training_time': training_time,
        'prediction_time': prediction_time,
        'y_pred_test': y_pred_test
    }

print("------- DETAILED EVALUATION - IRIS DATASET -------")

for name, result in iris_results.items():
    print(f"\n--- {name} ---")

    cm = confusion_matrix(y_iris_test, result['y_pred_test'])

    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=iris.target_names,
                yticklabels=iris.target_names)
    plt.title(f'Confusion Matrix - {name} (Iris)')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

    print("Classification Report:")
    print(classification_report(y_iris_test, result['y_pred_test'],
                              target_names=iris.target_names))

print("------- DETAILED EVALUATION - CANCER DATASET -------")

for name, result in cancer_results.items():
    print(f"\n--- {name} ---")

    cm = confusion_matrix(y_cancer_test, result['y_pred_test'])

    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Reds',
                xticklabels=cancer.target_names,
                yticklabels=cancer.target_names)
    plt.title(f'Confusion Matrix - {name} (Cancer)')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

    print("Classification Report:")
    print(classification_report(y_cancer_test, result['y_pred_test'],
                              target_names=cancer.target_names))

print("------- CROSS-VALIDATION - IRIS DATASET -------")

iris_cv_results = {}

for name, model in models.items():

    if name == 'Logistic Regression':
        model = LogisticRegression(random_state=42)
    elif name == 'Decision Tree':
        model = DecisionTreeClassifier(random_state=42)
    elif name == 'Naive Bayes':
        model = GaussianNB()
    elif name == 'SVM':
        model = SVC(kernel='linear', random_state=42)

    cv_scores = cross_val_score(model, X_iris_train_scaled, y_iris_train,
                               cv=5, scoring='accuracy')

    iris_cv_results[name] = {
        'cv_scores': cv_scores,
        'cv_mean': cv_scores.mean(),
        'cv_std': cv_scores.std()
    }

    print(f"{name}:")
    print(f"  CV Scores: {cv_scores}")
    print(f"  CV Mean: {cv_scores.mean():.4f} (+/- {cv_scores.std() * 2:.4f})")
    print(f"  Test Accuracy: {iris_results[name]['test_accuracy']:.4f}")
    print()

print("------- CROSS-VALIDATION - CANCER DATASET -------")

cancer_cv_results = {}

for name, model in models.items():

    if name == 'Logistic Regression':
        model = LogisticRegression(random_state=42)
    elif name == 'Decision Tree':
        model = DecisionTreeClassifier(random_state=42)
    elif name == 'Naive Bayes':
        model = GaussianNB()
    elif name == 'SVM':
        model = SVC(kernel='linear', random_state=42)

    cv_scores = cross_val_score(model, X_cancer_train_scaled, y_cancer_train,
                               cv=5, scoring='accuracy')

    cancer_cv_results[name] = {
        'cv_scores': cv_scores,
        'cv_mean': cv_scores.mean(),
        'cv_std': cv_scores.std()
    }

    print(f"{name}:")
    print(f"  CV Scores: {cv_scores}")
    print(f"  CV Mean: {cv_scores.mean():.4f} (+/- {cv_scores.std() * 2:.4f})")
    print(f"  Test Accuracy: {cancer_results[name]['test_accuracy']:.4f}")
    print()

comparison_data = []

for name in models.keys():
    comparison_data.append({
        'Dataset': 'Iris',
        'Model': name,
        'Test Accuracy': iris_results[name]['test_accuracy'],
        'CV Mean': iris_cv_results[name]['cv_mean'],
        'Training Time': iris_results[name]['training_time'],
        'Prediction Time': iris_results[name]['prediction_time']
    })

for name in models.keys():
    comparison_data.append({
        'Dataset': 'Cancer',
        'Model': name,
        'Test Accuracy': cancer_results[name]['test_accuracy'],
        'CV Mean': cancer_cv_results[name]['cv_mean'],
        'Training Time': cancer_results[name]['training_time'],
        'Prediction Time': cancer_results[name]['prediction_time']
    })

comparison_df = pd.DataFrame(comparison_data)
print("------- COMPREHENSIVE COMPARISON -------")
print(comparison_df.to_string(index=False))

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

iris_test_acc = [iris_results[name]['test_accuracy'] for name in models.keys()]
axes[0, 0].bar(models.keys(), iris_test_acc)
axes[0, 0].set_title('Test Accuracy - Iris Dataset')
axes[0, 0].set_ylabel('Accuracy')
axes[0, 0].tick_params(axis='x', rotation=45)

cancer_test_acc = [cancer_results[name]['test_accuracy'] for name in models.keys()]
axes[0, 1].bar(models.keys(), cancer_test_acc)
axes[0, 1].set_title('Test Accuracy - Cancer Dataset')
axes[0, 1].set_ylabel('Accuracy')
axes[0, 1].tick_params(axis='x', rotation=45)

iris_train_time = [iris_results[name]['training_time'] for name in models.keys()]
axes[1, 0].bar(models.keys(), iris_train_time)
axes[1, 0].set_title('Training Time - Iris Dataset')
axes[1, 0].set_ylabel('Time (seconds)')
axes[1, 0].tick_params(axis='x', rotation=45)

cancer_train_time = [cancer_results[name]['training_time'] for name in models.keys()]
axes[1, 1].bar(models.keys(), cancer_train_time)
axes[1, 1].set_title('Training Time - Cancer Dataset')
axes[1, 1].set_ylabel('Time (seconds)')
axes[1, 1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

print("------- ANALYSIS AND RECOMMENDATIONS -------")

print("\nBest Models by Dataset:")

best_iris_model = max(iris_results.keys(),
                     key=lambda x: iris_results[x]['test_accuracy'])
print(f"Iris Dataset: {best_iris_model} "
      f"(Accuracy: {iris_results[best_iris_model]['test_accuracy']:.4f})")

best_cancer_model = max(cancer_results.keys(),
                       key=lambda x: cancer_results[x]['test_accuracy'])
print(f"Cancer Dataset: {best_cancer_model} "
      f"(Accuracy: {cancer_results[best_cancer_model]['test_accuracy']:.4f})")

print("\nPerformance Analysis:")
print("1. Accuracy Performance")
print("2. Time Complexity")
print("3. Cross-Validation Stability")
print("4. Deployment Recommendations")